### ISSUE TITLE
Support for Pi Zero (W)

### ISSUE THREAD

**Issue by JanHBade** [eBUS/ttyebus#4]
or is that builtin with the "default" Rpi3 Mode?

**Comment by john30** [comment]
you need to try, I don't know if it works out of the box

**Comment by JanHBade** [comment]
pi@heizung:~$ ebusctl info
version: ebusd 3.4.v3.3-51-g57eae05
signal: acquired
symbol rate: 54
max symbol rate: 142
min arbitration micros: 24
max arbitration micros: 188
min symbol latency: 3
max symbol latency: 9
reconnects: 0
masters: 4
messages: 483
conditional: 0
poll: 0
update: 10
address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=HMU00;SW=0305;HW=0403", loaded "vaillant/08.hmu.csv"
address 10: master #2
address 15: slave #2, scanned "MF=Vaillant;ID=70000;SW=0419;HW=4603", loaded "vaillant/15.700.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd
address 71: master #9
address 76: slave #9, scanned "MF=Vaillant;ID=VWZ00;SW=0305;HW=0403"
address ec: slave, scanned "MF=Vaillant;ID=70000;SW=0419;HW=4603"

works :D
