### ISSUE TITLE
Enable Realtime?

### ISSUE THREAD

**Issue by JanHBade** [eBUS/ttyebus#5]
From a another project i found

```
echo "Enable realtime"
echo 'kernel.sched_rt_runtime_us=-1' > /etc/sysctl.d/10-ccu.conf || true
sysctl -w kernel.sched_rt_runtime_us=-1 || true

```
https://github.com/angelnu/docker-ccu/blob/master/deploy.sh

Maybe this can make this kernel driver better?

**Comment by john30** [comment]
why does it have to get better if there is no issue at all?

**Comment by JanHBade** [comment]
the other project uses a "realtime" uart driver too, so maybe you have a look...

no issue at all, right....
