### ISSUE TITLE
Compile Error on Kernel 5.4

### ISSUE THREAD

**Issue by SandnerSoft** [eBUS/ttyebus#6]
Hello,

The following error occurs when compiling on kernel 5.4:

`make -C /lib/modules/5.4.45-v7+/build M=/home/pi/ttyebus modules
make[1]: Verzeichnis „/home/pi/linux-9be502dfddaaa8f33790a7293900f8916c883944“ wird betreten
  CC [M]  /home/pi/ttyebus/ttyebusm.o
/home/pi/ttyebus/ttyebusm.c: In function ‘ttyebus_raspi_model’:
/home/pi/ttyebus/ttyebusm.c:805:12: error: implicit declaration of function ‘get_ds’; did you mean ‘get_fs’? [-Werror=implicit-function-declaration]
     set_fs(get_ds());
            ^~~~~~
            get_fs
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:266: /home/pi/ttyebus/ttyebusm.o] Fehler 1
make[1]: *** [Makefile:1706: /home/pi/ttyebus] Fehler 2
make[1]: Verzeichnis „/home/pi/linux-9be502dfddaaa8f33790a7293900f8916c883944“ wird verlassen
make: *** [Makefile:24: all] Fehler 2`

**Comment by SandnerSoft** [comment]
set_fs(get_ds()); 
changed to:
set_fs(KERNEL_DS);

solve this problem on newer kernel.

**Comment by Galileo53** [comment]
Corrected in version 1.8
Thank you for finding this issue
